### ISSUE TITLE
mesh.options and mesh.proto are symlinks

### ISSUE THREAD

**Issue by EntropyWorks** [meshtastic/Meshtastic-esp32#2]
Just looking around I see two files that are symlinks outside the repo.

    mesh.options -> ../MeshUtil/app/src/main/proto/mesh.options
    mesh.proto -> ../MeshUtil/app/src/main/proto/mesh.proto

Are these important for the build?

**Comment by geeksville** [comment]
They aren't _exactly_ required for the build because the bin/regen-protos.sh script uses the nanopb tool to generate C code from them.  They are actually currently located in the sister android app:  https://github.com/geeksville/Meshtastic-Android.

If you'd like to rebuild the C code from the .proto just clone that android repo as a peer directory to the esp32 project.  Thanks for the note though - this whole relationship needs to be cleaned up, mostly I wasn't wanting to have to deal with git submodules yet. ;-)

I'll leave this bug open as a reminder to clean this up.
